title: Tidy Data for Humanists
subtitle:
email: mlincoln@andrew.cmu.edu
description: |
  How do we “clean” complex humanities knowledge, especially when we may not yet know what kind of analysis we eventually want to do?
baseurl: '/tidy_humanities_data'
twitter_username: matthewdlincoln
github_username: mdlincoln

# Build settings
theme: minima

defaults:
  - scope:
      path: units
    values:
      layout: unit

permalink: /:path

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
